### ISSUE TITLE
помимо этого в cra лучше добавлять версию реакта и рект-дома руками из последних. Хотя бы 17 а лучше 18 уже. А тебе задача, напиши мне какая у тебя версия реакта в приложухе(с минорными версиями))

### ISSUE THREAD

**Issue by Bipbip215** [aaodegov/todo-list#1]
https://github.com/aaodegov/todo-list/blob/805ff57617525ec024ff30fffbbe645bce475a23/package.json#L57

**Comment by aaodegov** [comment]
> https://github.com/aaodegov/todo-list/blob/805ff57617525ec024ff30fffbbe645bce475a23/package.json#L57

насколько я вижу в нод модулях
и реакт-дом, и реакт - 16.14.0
